dist: trusty  # necessary for postgres 10 workaround
sudo: required
language: node_js
node_js:
  - "9.3"

cache:
  directories:
    - front/node_modules
    - back/node_modules

before_script:
  - psql --version
  - bash back/scripts/install-postgres-10.sh
  - psql --version
  - yarn install
  - yarn db:init
  - yarn db:fixture
  - yarn lint

before_deploy:
  - mkdir -p ~/bin
  - echo Created ~/bin
  - wget https://github.com/netlify/netlifyctl/releases/download/v0.3.1/netlifyctl-linux-amd64-0.3.1.tar.gz -O /tmp/netlifyctl.tgz
  - tar -xvf /tmp/netlifyctl.tgz -C ~/bin
  - export PATH=~/bin:$PATH
  - yarn build:front

deploy:
  provider: script
  script: netlifyctl deploy -s $NETLIFY_SITE_ID -A $NETLIFY_ACCESS_TOKEN -b ./front/dist
  skip_cleanup: true
