extends: airbnb
env:
  browser: true
  jest: true
rules:
  before-define: 0
  import/no-extraneous-dependencies: 0
  no-nested-ternary: 0
  no-use-before-define: 0
  react/prop-types: 0
  # TODO remove these exceptions
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
